---
- name: "Do a demo"
  hosts: groupA

  tasks:
    - name: demo task 1
      debug:
        msg: "this is task 1"

- name: "do another demo"
  hosts: groupB
  
  tasks: 
    - name: demo task 2
    - debug:
        msg: "this is task 2"
